# Generated by Django 3.2.6 on 2021-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
