# Generated by Django 3.2.6 on 2021-08-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_auto_20210827_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('registered_users', models.ManyToManyField(related_name='registered_olympiads', to='Bot.User')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiads', to='Bot.subject')),
            ],
        ),
    ]
