# Generated by Django 3.2.6 on 2021-09-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_auto_20210827_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
