# Generated by Django 3.2.6 on 2021-09-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
