# Generated by Django 3.2.6 on 2021-09-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_olympiad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_poorly_supplied',
            field=models.BooleanField(default=False),
        ),
    ]
